// Simple starter dataset for VibeScout
// You can add/remove fields as needed.

const places = [
  {
    id: 1,
    name: "Cosmic Garden Cafe",
    type: "cafe",
    cuisine: ["coffee", "brunch"],
    happyHour: true,
    city: "Austin",
    address: "123 Sunshine Ave",
    lat: 30.2672,
    lng: -97.7431,
    menuItems: ["margarita", "tacos", "chips and queso", "kids mac and cheese"],
    familyFriendly: true,
    petFriendly: true,
    hasPatio: true,
    hasPlayground: false,
    fenced: true,
    features: ["live_music", "outdoor_only"],
    priceLevel: "$$",
    vibes: ["chill", "outdoorsy", "creative"],
    hours: {
      mon: "7:00–22:00",
      tue: "7:00–22:00",
      wed: "7:00–22:00",
      thu: "7:00–22:00",
      fri: "7:00–23:00",
      sat: "8:00–23:00",
      sun: "8:00–21:00"
    }
  },
  {
    id: 2,
    name: "Little Longhorn Patio",
    type: "bar",
    cuisine: ["bar_food"],
    happyHour: true,
    city: "Austin",
    address: "456 Willow St",
    lat: 30.269,
    lng: -97.75,
    familyFriendly: true,
    petFriendly: true,
    hasPatio: true,
    hasPlayground: true,
    fenced: true,
    features: ["live_music", "trivia"],
    priceLevel: "$",
    vibes: ["lively", "local", "honky-tonk"],
    hours: {
      mon: "16:00–23:00",
      tue: "16:00–23:00",
      wed: "16:00–23:00",
      thu: "16:00–24:00",
      fri: "15:00–01:00",
      sat: "12:00–01:00",
      sun: "12:00–22:00"
    }
  },
  {
    id: 3,
    name: "Play Yard Cantina",
    type: "restaurant",
    cuisine: ["tex-mex", "tacos"],
    happyHour: true,
    city: "Austin",
    address: "789 Oak Lane",
    lat: 30.265,
    lng: -97.74,
    familyFriendly: true,
    petFriendly: false,
    hasPatio: true,
    hasPlayground: true,
    fenced: true,
    features: ["crafts"],
    priceLevel: "$$",
    vibes: ["family", "casual"],
    hours: {
      mon: "11:00–21:00",
      tue: "11:00–21:00",
      wed: "11:00–21:00",
      thu: "11:00–22:00",
      fri: "11:00–23:00",
      sat: "10:00–23:00",
      sun: "10:00–20:00"
    }
  },
  {
    id: 4,
    name: "Trailhead Brewing Co.",
    type: "brewery",
    cuisine: ["pub_food"],
    happyHour: true,
    city: "Austin",
    address: "321 River Rd",
    lat: 30.27,
    lng: -97.748,
    familyFriendly: true,
    petFriendly: true,
    hasPatio: true,
    hasPlayground: false,
    fenced: false,
    features: ["live_music", "outdoor_only"],
    priceLevel: "$$",
    vibes: ["craft", "outdoorsy"],
    hours: {
      mon: "15:00–22:00",
      tue: "15:00–22:00",
      wed: "15:00–22:00",
      thu: "15:00–23:00",
      fri: "13:00–24:00",
      sat: "12:00–24:00",
      sun: "12:00–21:00"
    }
  },
  {
    id: 5,
    name: "Market Yard Events",
    type: "event_space",
    cuisine: ["varies"],
    happyHour: false,
    city: "Austin",
    address: "654 Market St",
    lat: 30.268,
    lng: -97.742,
    familyFriendly: true,
    petFriendly: false,
    hasPatio: true,
    hasPlayground: false,
    fenced: true,
    features: ["crafts", "outdoor_only"],
    priceLevel: "$$",
    vibes: ["festive", "seasonal"],
    hours: {
      mon: "Closed",
      tue: "Closed",
      wed: "17:00–21:00",
      thu: "17:00–21:00",
      fri: "17:00–23:00",
      sat: "12:00–23:00",
      sun: "12:00–20:00"
    }
  }
];
